server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://132.232.52.199:3306/manage?autoReconnect=true
    username: root
    password: YFjo1oFIX6VO4lAL

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapxml/*.xml





